# Generated by Django 3.0.4 on 2020-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200414_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='checkbox_datetime',
            field=models.BooleanField(default=False, verbose_name='Checkbox'),
        ),
    ]
