# Generated by Django 3.0.4 on 2020-04-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_checkbox_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='checkbox_datetime',
        ),
    ]
