# Generated by Django 3.0.4 on 2020-05-01 22:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200501_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
