# Generated by Django 3.0.4 on 2020-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_checkbox_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
