# Generated by Django 3.0.4 on 2020-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200504_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
