# Generated by Django 3.0.4 on 2020-05-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_published_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_datetime',
        ),
    ]
