# Generated by Django 3.0.4 on 2020-05-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_published_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_time',
        ),
        migrations.AddField(
            model_name='post',
            name='published_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
