# Generated by Django 3.0.4 on 2020-05-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200509_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='checkbox_datetime',
            field=models.BooleanField(default=True, verbose_name='Checkbox'),
        ),
    ]
