# Generated by Django 3.0.4 on 2020-05-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200510_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='checkbox_datetime',
        ),
    ]
