# Generated by Django 3.0.4 on 2020-05-10 17:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_post_checkbox_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
